[[plugins]]
  package = "@netlify/plugin-nextjs"
  [functions]
  # Directory with serverless functions, including background 
  # functions, to deploy
  directory = "functions/"
[build]
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- apps/admin apps/docs apps/web"
